---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kwkhtmltopdf-config
data:
  {{- if .Values.no_storage_cleaning }}
  NO_STORAGE_CLEANING: {{ .Values.no_storage_cleaning | default "True" | quote }}
  {{- end }}
