apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odyssey.fullname" . }}
  labels:
    {{- include "odyssey.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "odyssey.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "odyssey.labels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/ini: {{ include "odyssey.conf.1.0.0" . | sha256sum }}
        {{- if .Values.spec.annotations }}
        {{- tpl (toJson .Values.spec.annotations) . | fromJson | toYaml |  nindent 8 }}
        {{- end }}
        {{- with .Values.additionalAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "odyssey.fullname" . }}-config
        {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: odyssey
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["/etc/odyssey/odyssey.conf"]
          ports:
            - name: odyssey
              containerPort: {{ .Values.internalPort }}
            - name: odysseymetrics
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: {{ .Values.internalPort }}
          {{- if .Values.livenessProbe}}
          livenessProbe:
           {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              subPath: odyssey.conf
              mountPath: /etc/odyssey/odyssey.conf
            {{- with .Values.volumeMounts }}
            # extra volumes mounts
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
