---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ default (include "odyssey.fullname" .) }}
  labels:
    {{- include "odyssey.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}  
  selector:
    matchLabels:
    {{- include "odyssey.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: "/metrics"
    interval: {{ .Values.metrics.scrapeInterval }}
