{{- if or .Values.mailpit.ui.authFile.enabled .Values.mailpit.smtp.authFile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.mailpit.ui.authFile.enabled }}
  ui.htpasswd: {{- include "common.tplvalues.render" ( dict "value" .Values.mailpit.ui.authFile.htpasswd "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.mailpit.smtp.authFile.enabled }}
  smtp.htpasswd: {{- include "common.tplvalues.render" ( dict "value" .Values.mailpit.smtp.authFile.htpasswd "context" $ ) | nindent 4 }}
  {{- end }}
{{- end }}
