apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.names.fullname" . }}-network-policy
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.service.http.annotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mailpit
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: odoo
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: odoo-queue
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: traefik
      podSelector:
        matchLabels:
          app.kubernetes.io/name: traefik
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-prometheus-stack
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus

