apiVersion: batch/v1
kind: CronJob
metadata:
  name: filestore-offsite-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      backoffLimit: 1
      template:
        metadata:
          labels:
            azure.workload.identity/use: "true"
        spec:
          serviceAccountName: filestore
          restartPolicy: Never
          nodeSelector:
            odoo.camptocamp.com/nodepool: miscapps
            odoo.camptocamp.com/environment: prod
          containers:
          - name: rclone
            image: rclone/rclone:latest
            command: ["rclone"]
            args: ["copy", "azure:", "offsite:", "--immutable", "--checksum", "--ignore-size", "--use-json-log"]
            env:
              - name: RCLONE_AZUREBLOB_ACCOUNT
                valueFrom:
                  secretKeyRef:
                    name: azure-storage
                    key: filestore_account
            envFrom:
              - configMapRef:
                  name: offsite-storage-config
              - secretRef:
                  name: offsite-storage-secret
