---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: offsite-backups
  target:
    name: azure-storage
    creationPolicy: Owner
  data:
    - secretKey: celebrimbor_account
      remoteRef:
        key: CELEBRIMBOR-ACCOUNT
    - secretKey: celebrimbor_storage_name
      remoteRef:
        key: CELEBRIMBOR-STORAGE
    - secretKey: filestore_account
      remoteRef:
        key: FILESTORE-ACCOUNT
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: offsite-storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: offsite-backups
  target:
    name: offsite-storage-secret
    creationPolicy: Owner
  data:
    {{- if eq .Values.offsiteStorageKind "s3" }}
    - secretKey: RCLONE_S3_ACCESS_KEY_ID
      remoteRef:
        key: OFFSITE-S3-ACCESS-KEY
    - secretKey: RCLONE_S3_SECRET_ACCESS_KEY
      remoteRef:
        key: OFFSITE-S3-SECRET-KEY
    {{- else if eq .Values.offsiteStorageKind "swift" }}
    - secretKey: RCLONE_SWIFT_USER
      remoteRef:
        key: OFFSITE-SWIFT-USER
    - secretKey: RCLONE_SWIFT_KEY
      remoteRef:
        key: OFFSITE-SWIFT-KEY
    - secretKey: RCLONE_SWIFT_TENANT
      remoteRef:
        key: OFFSITE-SWIFT-TENANT
    {{- end }}
