---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.identity.clientID }}
    azure.workload.identity/tenant-id: {{ .Values.identity.tenantID }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: celebrimbor
  annotations:
    azure.workload.identity/client-id: {{ .Values.identity.clientID_celebrimbor }}
    azure.workload.identity/tenant-id: {{ .Values.identity.tenantID }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filestore
  annotations:
    azure.workload.identity/client-id: {{ .Values.identity.clientID_filestore }}
    azure.workload.identity/tenant-id: {{ .Values.identity.tenantID }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filestore-restore
  annotations:
    azure.workload.identity/client-id: {{ .Values.identity.clientID_filestore_restore }}
    azure.workload.identity/tenant-id: {{ .Values.identity.tenantID }}
