{{- with .Values.odoo.secrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: odoo-secret{{- include "odoo-cs-suffix" $ }}
  labels:
    {{- include "odoo.labels" $ | nindent 4 }}
data:
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
{{- end }}
