---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: odoo-ratelimit{{- include "odoo-cs-suffix" . }}
spec:
  rateLimit:
    average: {{ .Values.rateLimit.average }}
    burst: {{ .Values.rateLimit.burst }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https{{- include "odoo-cs-suffix" . }}
spec:
  redirectScheme:
    scheme: https

{{- if $.Values.waf.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: waf-authforward{{- include "odoo-cs-suffix" . }}
spec:
  forwardAuth:
    address: {{ .Values.waf.address }}
    trustForwardHeader: {{ .Values.waf.trustForwardHeader }}
{{- end }}

