{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "odoo.name" . }}
  namespace: 
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: traefik
      podSelector:
        matchLabels:
          app.kubernetes.io/name: traefik
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-prometheus-stack
      podSelector:
        matchLabels:
          app: kube-prometheus-stack-operator
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: bs-kwkhtmltopdf01250
      podSelector:
        matchLabels:
          app.kubernetes.io/name: kwkhtmltopdf
    {{- with .Values.networkPolicies.explicitNamespacesSelector }}
    - namespaceSelector:
        {{- toYaml . | nindent 12 }}
    {{- end }}

  podSelector: {}
  policyTypes:
    - Ingress
{{- end}}
