{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "odoo.name" . }}
  namespace: 
spec:
  ingress:
    - from: 
      - podSelector:                                                              
          matchLabels:                                                            
            app.kubernetes.io/name: traefik
    - from:
      - podSelector:                                                              
          matchLabels:                                                            
            app: kube-prometheus-stack-operator
    - from:
      - podSelector:                                                              
          matchLabels:
            app.kubernetes.io/name: kwkhtmltopdf
  podSelector: {}
  policyTypes:
    - Ingress
{{- end}}
