apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: odoohealthmonitor
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}  
  selector:
    matchLabels:
      {{- include "odoo.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: odoohealthz
    interval: {{ .Values.odoo.metrics.scrapeInterval }}
