apiVersion: v1
kind: ConfigMap
metadata:
  name: celebrimbor-config
data:
  UWSGI_PROCESSES: {{ .Values.celebrimbor.uwsgi_processes | default "1" | quote }}
  EXCLUDE_DATABASE: {{ .Values.celebrimbor.exclude_database | default "template0,template1,postgres" }}
  GPG_PROVIDER: {{ .Values.celebrimbor.gpg_provider | default "env" }}
  SESSION_TYPE: {{ .Values.celebrimbor.session_type | default "filesystem" }}
  SESSION_KEY_PREFIX: {{ .Values.celebrimbor.session_key_prefix | default "celebrimbor:" | quote }}
  TOKEN_KEY_PREFIX: {{ .Values.celebrimbor.token_key_prefix | default "celebrimbor-token:" | quote }}
  FLEXIBLE_SERVER_RG: {{ .Values.celebrimbor.flexible_server_rg | default "flexible-servers-rg" | quote }}
  DUMP_ALL_SCHEDULE:  {{ .Values.celebrimbor.internal_cron.dump_all_schedule }}
  VACUUM_ALL_SCHEDULE: {{ .Values.celebrimbor.internal_cron.vacuum_all_schedule }}
  DISABLE_CRON_JOBS: {{ .Values.celebrimbor.internal_cron.disable_all | default "False" | quote }}
  LOG_DEBUG: {{ .Values.celebrimbor.log_debug | default "False" | quote }}
  TMPDIR: {{ .Values.celebrimbor.tmpdir | default "/tmp" }}
