{{- if .Values.celebrimbor.key_backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: key-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- with .Values.additionalLabels }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.serviceAccount }}
          serviceAccountName: {{ . }}
          {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          containers:
          - name: key-backup
            image: "{{ .Values.image.key_backup.repository }}:{{ .Values.image.key_backup.component }}-{{ .Values.image.version }}"
            imagePullPolicy: Always
            envFrom:
              - secretRef:
                  name: gpg
              - secretRef:
                  name: keybackup
{{ end }}
