---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: celebrimbor
  target:
    name: azure-app
    creationPolicy: Owner
  data:
    - secretKey: CLIENT_ID
      remoteRef:
        key: CLIENT-ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: CLIENT-SECRET
    - secretKey: TENANT_ID
      remoteRef:
        key: TENANT-ID
    - secretKey: NON_INTERACTIVE_OID
      remoteRef:
        key: NON-INTERACTIVE-OID
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gpg
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: celebrimbor
  target:
    name: gpg
    creationPolicy: Owner
  data:
    - secretKey: GPG_KEYVAULT_NAME
      remoteRef:
        key: GPG-KEYVAULT-NAME
    - secretKey: GPG_KEYVAULT_SECRET
      remoteRef:
        key: GPG-KEYVAULT-SECRET
    - secretKey: GPG_RECIPIENTS
      remoteRef:
        key: GPG-RECIPIENTS
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: celebrimbor
  target:
    name: redis
    creationPolicy: Owner
  data:
    - secretKey: SESSION_REDIS_URL
      remoteRef:
        key: SESSION-REDIS-URL
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: celebrimbor
  target:
    name: storage
    creationPolicy: Owner
  data:
    - secretKey: AZURE_ACCOUNT_URL
      remoteRef:
        key: AZURE-ACCOUNT-URL
    - secretKey: AZURE_STORAGE_NAME
      remoteRef:
        key: AZURE-STORAGE-NAME
    - secretKey: AZURE_ANON_STORAGE_NAME
      remoteRef:
        key: AZURE-ANON-STORAGE-NAME
    - secretKey: AZURE_SUBSCRIPTION_ID
      remoteRef:
        key: AZURE-SUBSCRIPTION-ID
{{- with .Values.celebrimbor.additionalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: additional-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: celebrimbor
  target:
    name: additional-secrets
    creationPolicy: Owner
  data:
    {{- range . }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ . | replace "_" "-" }}
    {{- end }}
{{- end }}
{{- if .Values.celebrimbor.key_backup.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keybackup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: celebrimbor
  target:
    name: keybackup
    creationPolicy: Owner
  data:
    - secretKey: LPASS_LOGIN
      remoteRef:
        key: KEYBACKUP-LPASS-LOGIN
    - secretKey: LPASS_PASSWORD
      remoteRef:
        key: KEYBACKUP-LPASS-PASSWORD
{{- end }}
