apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: celebrimbor
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://{{ .Values.keyvaultName }}.vault.azure.net/"
      serviceAccountRef:
        name: "{{ .Values.serviceAccountName }}"
