apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.identity.clientID }}
    azure.workload.identity/tenant-id: {{ .Values.identity.tenantID }}
